sudo: false


git:
  depth: 1

matrix:
  include:

    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - CXXFLAGS=-std=c++17

    - os: linux
      python: "3.6-dev"
      language: python
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - CXXFLAGS=-std=c++17
        - PYTHON="3.6-dev"


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "${MATRIX_EVAL}";
    fi
  - uname -a
  - $CXX --version
  - $CC --version
  - python --version
  - python3 --version


install:
  # install dependencies for python tests
  - if [[ "$PYTHON" ]]; then
      python3 -m pip install path.py ;
    fi
  # install vcpkg and dependencies
  - pwd
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install catch2 orc pybind11 zstd
  - cd ..



script:
  # build and install stryke cpp
  - pwd
  - mkdir -p build && cd build
  - if [[ "$PYTHON" ]]; then
      cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_PYTHON_BINDING=ON -DBUILD_EXAMPLES=ON -DBUILD_UNIT_TESTS=ON ;
      make ;
      make install ;
    elif
      cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_EXAMPLES=ON -DBUILD_UNIT_TESTS=ON ;
      make ;
    fi
  # - python3 setup.py install

  # Test CPP
  - ./unit-test
  - cd ..

  # Test Python
  - if [[ "$PYTHON" ]]; then
      python3 -m pytest tests/python ;
    fi

