sudo: false

language: cpp

git:
  depth: 1

matrix:
  include:

    - os: linux
      dist: trusty
      compiler: gcc
      python: 3.5-dev
      env:
          - COMPILER=g++-8
          - CXXFLAGS=-std=c++17
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'git']

    - os: linux
      dist: trusty
      compiler: gcc
      python: 3.6-dev
      env:
          - COMPILER=g++-8
          - CXXFLAGS=-std=c++17
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'git']


before_install:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - uname -a
  - $CXX --version
  - python --version
  - python3 --version


install:
  # install vcpkg and dependencies
  - pwd
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install catch2 orc pybind11 zstd
  - cd ..

  # install dependencies for python tests
  - python3 -m pip install path.py


script:
  # build and install stryke cpp
  - pwd
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_PYTHON_BINDING=ON -DBUILD_EXAMPLES=ON -DBUILD_UNIT_TESTS=ON
  - make
  - make install
  # - python3 setup.py install

  # Test CPP
  - ./unit-test
  - cd ..

  # Test Python
  - python3 -m pytest tests/python

